### ISSUE TITLE
[about:addons] Laserlike company name and URL from "By" section wrongly redirect to GitHub page

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [LaserlikeInc/firefox-addon#74] opened 2018-08-09 09:42 UTC
**[Affected versions]:**
- Firefox 61.0.2 and above

**[Affected Platforms]:**
- All Windows
- All MacOS
- All Linux

**[Prerequisites]:**
- Test Pilot add-on was already installed on a new profile.
- Advance experiment was already enabled from Test Pilot website on the same profile

**[Steps to reproduce]:**
1. Open Firefox browser with the profile from prerequisites and navigate to "about:addons" page.
2. Click the "Extensions" section button and then double click on "Advance" experiment entry.  
3. Observe the string displayed at "By" section, under the experiment add-on title and version.
4. Click on the string and observe where you are redirected.

**[Expected result]:**
- Step 3: The Laserlike company name and website displayed in the section.
- Step 4: You are redirected to https://www.laserlike.com/ page.

**[Actual result]:**
- Step 3: The Laserlike company name and website displayed in the section.
- Step 4: You are wrongly redirected to Laserlike GitHub page.
 
**[Notes]:**
- Since the string clearly displays the company website URL and since we already have the GitHub page in the "Homepage" section, I assume we shouldn't have the same URL in both sections.
- Here is a screen recording of the issue: https://goo.gl/9dFRj6.

**Comment by chuckharmston** [comment] 2018-08-15 14:59
Per @sguo-laserlike, this should be fixed.

**Closed by chuckharmston** 2018-08-15 14:59 UTC

**Comment by Softvision-RemusDranca** [comment] 2018-08-31 14:42
I have verified this issue using the latest Advance (0.9.45816) version and the issue is no longer reproducible. Tested on Windows 10 x64, Mac 10.13 and Arch Linux.
