### ISSUE TITLE
Disable the extension in Private Browsing Windows

### ISSUE THREAD

**Issue by groovecoder** [LaserlikeInc/firefox-addon#59] opened 2018-08-06 15:01 UTC
Please disable the extension in private browsing windows - there should be no browser history tracking in private browsing windows. This may also fix #35, #36, and #37.

**Comment by chuckharmston** [comment] 2018-08-06 18:07
I'll leave this open for the LL team to verify, but I believe this is already in place (and couldn't reproduce any data leaving the client in PBM).

CC @sriniven

**Comment by groovecoder** [comment] 2018-08-06 18:36
Recording and how I did it ...

1. `npm start`
2. Open Browser Console
3. Go to "Network" tab
4. Filter requests by "laserlike"
5. Open Private Browsing Window
6. In private window, go to news.google.com
   * Observe a request sent to https://feed.laserlike.com/searchlike/api/v1/related with `POST` params including https://news.google.com
7. Click a news headline
   * Observe a request sent to https://feed.laserlike.com/searchlike/api/v1/related with `POST` params including http://abc7chicago.com/66-shot-12-fatally-in-chicago-weekend-shootings/3892234/

![laserlike-pbm](https://user-images.githubusercontent.com/71928/43734393-32e3cf78-997d-11e8-95f0-d03f6be9a68c.gif)

**Comment by sriniven** [comment] 2018-08-06 18:38
Luke, in private browsing mode, we were planning to show "Read Next" but
not store the URL for personalizing future For You.

Does this work? Or is the expectation that we won't show anything to the
user and completely disable the extension?

**Comment by groovecoder** [comment] 2018-08-06 18:42
@chuckharmston can speak to user expectation & intention for this particular feature.

The main thing is that we should not be sending any requests to a 3rd party that include the pages the user viewed in Private Browsing (or with Tracking Protection enabled).

**Comment by chuckharmston** [comment] 2018-08-06 18:44
@sriniven Since Read Next requires sending browsing history over the wire, we should disable that as well.

**Comment by chuckharmston** [comment] 2018-08-07 01:32
@sriniven Is this ready to be tested?

**Comment by chuckharmston** [comment] 2018-08-07 01:46
<img width="1680" alt="screen shot 2018-08-06 at 7 43 03 pm" src="https://user-images.githubusercontent.com/23885/43749379-17862b70-99b1-11e8-89ea-feb0a91b79ea.png">

On 0.9.35230 I'm still seeing requests made with a user ID, as shown in the screenshot above.

Rather than try to work around this or run any sort of detection, could you  set [`"incognito": "not_allowed"`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/incognito) in the manifest? Per the documentation, it should make private tabs and windows invisible to the extension.

**Comment by sriniven** [comment] 2018-08-07 01:51
Ok, will do that.

Thanks
Cheenu

**Comment by SoftVision-CosminMuntean** [comment] 2018-08-07 09:06
I have verified this issue using latest Laserlike (0.9.41) version and the "While browsing privately or with tracking protection..." message is correctly displayed when you are in private window. Also, I haven't observed any Laserlike requests on Network tab.
Tested on Windows 7 x64, Mac 10.13 and Arch Linux.

Considering this I will close this issue as verified fixed.

**Closed by SoftVision-CosminMuntean** 2018-08-07 09:06 UTC
Labels: [QA]:Blocker issue

**Comment by groovecoder** [comment] 2018-08-07 12:52
Also verified: I don't see any network requests sent to laserlike from Private Window now.

**Comment by groovecoder** [comment] 2018-08-07 12:52
Thanks for turning this around so quickly!
