### ISSUE TITLE
The "Read Next" section is no longer populated if the browser is restarted after the "Override DoNotTrack" option is enabled

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [LaserlikeInc/firefox-addon#88] opened 2018-08-31 14:20 UTC
**[Affected versions]:**
- Firefox 61.0.2 and above

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have the latest Laserlike (0.9.45) version installed on a new Firefox profile.
- Have the Tracking Protection or Do Not Track option enabled.

**[Steps to reproduce]:**
1. Open browser with the profile from prerequisites.
2. Click the "Advance" toolbar icon.
3. Click the "Settings" button and enable the "Override DoNotTrack" option.
4. Navigate to any website and observe the "Read Next" section.
5. Restart the browser.
6. Navigate to a different website and observe the "Read Next" section.

**[Expected result]:**
Step 4 & Step 5: The "Read Next" section is populated.

**[Actual result]:**
Step 4: The "Read Next" section is populated.
Step 5: The "Read Next" section is no longer populated.

**[Notes]**
- However, if you disable and re-enable the "Override DoNotTrack" option, the section is again populated until you restart the browser.
- Here is a screen recording with the issue: 
![rread next section not populated](https://user-images.githubusercontent.com/19226534/44917783-ffbf3280-ad41-11e8-9912-a6d64d5cd864.gif)

**Comment by sg-laserlike** [comment] 2018-09-04 20:13
This is fixed in the latest master branch. Please retest.

**Comment by Softvision-RemusDranca** [comment] 2018-09-05 11:26
I have verified this issue using the latest "Advance" (0.9.45936) version and the issue is no longer reproducible. Tested on Windows 10 x64, Mac 10.13 and Arch Linux.

**Closed by Softvision-RemusDranca** 2018-09-05 11:26 UTC
Labels: [QA]:Major issue
