### ISSUE TITLE
The "For Your" section is no longer populated

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [LaserlikeInc/firefox-addon#33] opened 2018-07-27 12:55 UTC
[Affected versions]:
- Firefox 61.0.1 and above

[Affected platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have the latest Laserlike (0.9.26) version installed on a new Firefox profile.
- Have the Laserlike sidebar open.
- Have at least 20 different links opened in different tabs, in order to have browsing history.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites.
2. Navigate to at least 3 different websites in different tabs.
3. Observe the "For You" section.

[Expected result]:
- The section is populated with relevant content, considering the browsing history.

[Actual result]:
- The section is not populated and the "Nothing to see right now" message is displayed.

[Notes]:
- I've waited and kept browsing for 30 minutes, and the "For You" section was still not populated.
- Here is a screen recording with this issue:
![laserlike - for you section](https://user-images.githubusercontent.com/31244235/43321656-431efeaa-91b5-11e8-9793-7ee6c043373d.gif)

**Comment by SoftVision-CosminMuntean** [comment] 2018-08-03 14:44
I have verified this issue using latest Laserlike (0.9.32) version and the "For You" section is populated. But, compared with 0.9.24 version, it seems that the "For You" section is harder to populate. You have to navigate a lot more articles. Has something changed or is there an issue?

Can you guys confirm that this is intended behavior? Also can you give us more information about how the "For You" section is populated and after which kind of articles/pages visited the section will be populated?

**Comment by chuckharmston** [comment] 2018-08-03 14:52
This is the intended behavior; they stopped trying to use browser history prior to extensioon installation to populate that section.

**Comment by SoftVision-CosminMuntean** [comment] 2018-08-03 15:04
Thanks @chuckharmston! Considering this I will close this issue as verified fixed.

**Closed by SoftVision-CosminMuntean** 2018-08-03 15:04 UTC
Labels: [QA]:Major issue
