### ISSUE TITLE
[about:addons] Default add-ons puzzle icon is displayed instead of the Advance logo

### ISSUE THREAD

**Issue by SoftVision-PaulOiegas** [LaserlikeInc/firefox-addon#73] opened 2018-08-09 08:59 UTC
**[Affected versions]:**
- Firefox 61.0.2 and above

**[Affected Platforms]:**
- All Windows
- All MacOS
- All Linux

**[Prerequisites]:**
- Test Pilot add-on was already installed on a new profile.

**[Steps to reproduce]:**
1. Open Firefox browser with the profile from prerequisites and navigate to https://testpilot.firefox.com/experiments page.
2. Scroll down to the current experiments section and click the "Advance" experiment card.
3. Click the "Enable Advance" button from top let side and then click the "Add" button on doorhanger.
4. Open a new tab and navigate to "about:addons" and click the "Extensions" section button.
5. Observe the Advance experiment logo displayed on the page.

**[Expected result]:**
- The Advance experiment logo is correctly displayed.

**[Actual result]:**
- The default add-ons puzzle icon is displayed instead. 
 
**[Notes]:**
- Here is a screenshot of the issue:

![advance icon about_addons](https://user-images.githubusercontent.com/17258026/43888750-1690d30c-9bcb-11e8-80db-9372525b80ad.png)

**Comment by chuckharmston** [comment] 2018-08-15 14:59
Per @sguo-laserlike, this should be fixed.

**Closed by chuckharmston** 2018-08-15 14:59 UTC

**Comment by Softvision-RemusDranca** [comment] 2018-08-31 14:41
I have verified this issue using the latest Advance (0.9.45816) version and the issue is no longer reproducible. Tested on Windows 10 x64, Mac 10.13 and Arch Linux.
